# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ded79cf37e22c1084f7c510071dce19cb2bf73fe42d07f5580b75aa016855831e456f2208531742522c5abbff49b2e08ed469a2cb690c70f0c2f940712173d

test:
  secret_key_base: 4a5ddab5f7a684ba4f00f7f7bb59b3aea2b84e66a44d00ec1726bf0f10a0a93fe1933609a8d3982470b1c4eaf0e451cfdc3265c52a370b883869ff25dc306f6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
